name: Test or Release

on:
  push:
    branches:
      - main

jobs:
  Lint-and-Test:
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_TOKEN }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python: ["3.13"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Sync project
        run: |
          uv add ruff --dev
          uv add pytest-cov --dev
          uv sync --all-extras --dev
      - name: Run ruff for code lint and format
        run: |
          uv run ruff format
          uv run ruff check --fix
      - name: Run pytest include codecov
        run: |
          uv run pytest --cov --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sicheng1806/ml-sicheng
  Release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: Lint-and-Test
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Build project
        run: |
          uv sync
          uv build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: 不稳定且不断替换的测试版本
          files: ${{ github.workspace }}/dist/*
          prerelease: true
          draft: false
