name: code-lint-and-test

on:
    push:
        branches:
            - main

jobs:
    lint-and-test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-24.04]
                python: ["3.13"]

        steps:
            - name: Check out
              uses: actions/checkout@v4
            - name: Install uv
              uses: astral-sh/setup-uv@v4
              with:
                enable-cache: true
            - name: Install python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python }}
            - name: Sync project
              run: |
                uv add ruff --dev
                uv add pytest-cov --dev
                uv sync --all-extras --dev
            - name: Run ruff for code lint and format
              run: |
                uv run ruff format
                uv run ruff check --fix
            - name: Run pytest include codecov
              run: |
                uv run pytest --cov --cov-report=xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                slug: sicheng1806/ml-sicheng
