name: Release

on:
  push:
    tags:
        "v*"

jobs:
  Release:
    permissions:
      contents: write
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Test
        run: uv run pytest
      - name: Build project
        run: |
          uv sync
          uv build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: 不稳定且不断替换的测试版本
          files: ${{ github.workspace }}/dist/*
          prerelease: true
          draft: false
